apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-system
  template:
    metadata:
      name: user-pod-container
      labels: 
        app: user-management-system
    spec:
      containers:
          - name: user-management-code-container
            image: vajidhussain/user-management-system:latest
            ports:
              - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata: 
  name: user-code-service-service
  labels:
    service: user-code-service
spec:
  type: NodePort
  selector:
    app: user-management-system
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002
      